export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const REFRESH_USER = 'REFRESH_USER';
export const GET_TOKEN = 'GET_TOKEN';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';


export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
